### PR TITLE
see ya, snu

### PR DESCRIPTION
**Pull request by PeterAustinMoore**
Before:
Full snuffleupdata site with the markdowns for each snu + images of each snu. 

After:
- Remove the snuffies
- Remove the descriptive text
- Replace website with just classic snu
- Bump ruby version + dependencies

** Site will be decommissioned shortly **
** This is a stop gap process while we move snu's to other venues **

### CODE REVIEW

**Comment by chrismetcalf** [comment]
😢

**Comment by carmstrong** [comment]
New mascot who dis

**Comment by chrismetcalf** [comment]
Vote @carmstrong for the New Snu! 🗳️

**Comment by TranquilMarmot** [comment]
This is an outrage! 😤

**Pull request merged**
